#数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oa?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    #type: com.alibaba.druid.pool.DruidDataSource
#编码格式
server:
  tomcat:
    uri-encoding: utf-8
#session生命周期
  servlet:
    session:
      timeout: 30m